# Generated by Django 4.2.6 on 2023-10-17 09:32

import ChatBot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[ChatBot.models.validate_digit_phone_number]),
        ),
    ]
