# Generated by Django 4.2.6 on 2023-10-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0002_alter_messagemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='meessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/message_file/'),
        ),
    ]
