# Generated by Django 4.2.6 on 2024-01-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0003_alter_messagemodel_meessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/user_profile/'),
        ),
    ]
